apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-app-set
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: dev
  - clusters:
      selector:
        matchLabels:
          environment: uat
  - clusters:
      selector:
        matchLabels:
          environment: prod
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/CyrusTC/argosam
        targetRevision: HEAD
        path: guestbook-set/overlays/{{metadata.labels.environment}}
        kustomize:
          commonAnnotationsEnvsubst: true
          commonAnnotations:
            argo-cluster-name: '{{name}}'
            argo-cluster-server: '{{server}}'
            "alb.ingress.kubernetes.io/group.name": '{{name}}'
      destination:
        server: '{{server}}'
        namespace: guestbook-app
