apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CyrusTC/argosam
    targetRevision: HEAD
    path: guestbook/overlays/sit
  destination:
    server: dev-cluster-1.30-1
    namespace: guestbook-app
